# ICE 2 Introduction to Data Manipulation in Python - PART 2

Yiran Charlotte Wang

## Objectives:
1. Index data
2. Create data mask for filtering
3. Combine datasets
4. Aggregate, group data as well as create pivot tables

## Data Indexing

### Data manipulation in array

In [1]:
import numpy as np

In [2]:
# We are generating random number here, so it will be different every time.
# Setting a seed = 123 help us generate the exact same numbers
# Next time when we call 123 for reproducibility purposes.
# You can use any number as a seed.
# Need to be put in the same code
np.random.seed(123)

# Create a array of 10 random integers in the interval [0, 100)
m1 = np.random.randint(0, 100, size = 10)
# Create a 3 x 4 array of in the interval [0, 10)
m2 = np.random.randint(10, size=(3, 4))

# "\n" is used to start a new line
print("The one-dimensional array looks like this:\n", m1)
print("The two-dimensional array looks like this:\n", m2)

The one-dimensional array looks like this:
 [66 92 98 17 83 57 86 97 96 47]
The two-dimensional array looks like this:
 [[9 0 0 9]
 [3 4 0 0]
 [4 1 7 3]]


#### Accessing single elements

Indexing in NumPy is actually pretty straight-forward.
The i-th value , counting from zero, can be accessed by specifying the desired index in square brackets [].

In [3]:
m1[1]

92

In [4]:
# You can count from the end
m1[-2]

96

In [5]:
# Same rules apply for multi-dimensional array
m2[2, 1] # Third row, Second column

1

#### Accessing subarrays

In [6]:
# Just as we can use square brackets [] to access individual array elements,
# We can also use them to access subarrays with the slice notation, marked by the colon : character.

Note:
The standard expression should be x[start:stop:step]

where x is the array;

start is the starting position;

stop is the stopping position;

and step is the length of counting step.

If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1.

In [7]:
# accessing the second, forth, and sixth element
m1[1:7:2]

array([92, 17, 57])

In [8]:
# accessing the first five elements
m1[:5]

array([66, 92, 98, 17, 83])

In [9]:
# accessing elements after the sixth element
m1[5:]

array([57, 86, 97, 96, 47])

In [10]:
# every other elements
m1[::2]

array([66, 98, 83, 86, 96])

In [11]:
# Challenge: how would you access every other element starting from the second?
m1[1::2]

array([92, 17, 57, 97, 47])

In [12]:
# all elements, reversed
m1[::-1]

array([47, 96, 97, 86, 57, 83, 17, 98, 92, 66])

Multi-dimensional slices work in the same way, with multiple slices separated by commas. For example:

In [13]:
# first two rows, first three columns
m2[:2,:3]

array([[9, 0, 0],
       [3, 4, 0]])

In [14]:
# first column
m2[:,:1]

array([[9],
       [3],
       [4]])

In [15]:
#or
m2[:,0]

array([9, 3, 4])

In [16]:
# first row
m2[0, :]

array([9, 0, 0, 9])

In [17]:
# This could be written in a compact format
m2[0]

array([9, 0, 0, 9])

In [18]:
# you can build masking to an array
# this accesses all the elements greater than 1
m2[m2 > 1]

array([9, 9, 3, 4, 4, 7, 3])

#### Some other useful tricks for array

np.concatenate: stacking arrays of same dimension together.

np.vstack: similar to np.concatenate, but clearer. Stack arrays together vertically.

np.hstack: Stack arrays together horizontally.

In [19]:
grid = np.array([[1,2,3],
               [4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [20]:
np.vstack([grid,grid+1])
#grid + 1 = every element in grid increments 1

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4],
       [5, 6, 7]])

In [21]:
np.hstack([grid,grid+1])

array([[1, 2, 3, 2, 3, 4],
       [4, 5, 6, 5, 6, 7]])

Each array has attributes:
- ndim (the number of dimensions),
- shape (the size of each dimension),
- and size (the total size of the array)

np.reshape() an array
https://numpy.org/doc/stable/reference/generated/numpy.reshape.html

np.split() an array
https://numpy.org/doc/stable/reference/generated/numpy.split.html
- hsplit
- vsplit

In [22]:
np.reshape(grid,[3,2])

array([[1, 2],
       [3, 4],
       [5, 6]])

### Data manipulation in Series

In [23]:
import pandas as pd
s1 = pd.Series([0.25, 0.5, 0.75, 1.0],
            index=['a', 'b', 'c', 'd'])
s1

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [24]:
# You can also use explicit index.
s1['b']

0.5

In [25]:
# You can also use implicit index or array/Python style index as well.
s1[1] 

0.5

In [26]:
# slicing by explicit index
s1['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [27]:
#or
s1[0:3]

a    0.25
b    0.50
c    0.75
dtype: float64

In [28]:
s1[(s1 > 0.3) & (s1 < 0.8)]

b    0.50
c    0.75
dtype: float64

However, these slicing and indexing conventions can be a source of confusion. For example, if your Series has an explicit integer index, an indexing operation such as data[1] will use the explicit indices, while a slicing operation like data[1:3] will use the implicit Python-style index.

In [29]:
s2 = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
s2

1    a
3    b
5    c
dtype: object

In [30]:
# explicit index when indexing
s2[1]

'a'

In [31]:
#s2['1']
# This will return error because index `1` is stored as a number.

In [32]:
s2[1:3]

3    b
5    c
dtype: object

Because of this potential confusion in the case of integer indexes, Pandas provides some special indexer attributes that explicitly expose certain indexing schemes.

These are not functional methods, but attributes that expose a particular slicing interface to the data in the Series.

In [33]:
#First, the loc attribute allows indexing and slicing that always references the explicit index:
s2.loc[1:3]

1    a
3    b
dtype: object

In [34]:
#The iloc attribute allows indexing and slicing that always references the implicit array-style/Python-style index:
s2.iloc[1:3]

3    b
5    c
dtype: object

### Data Indexing in DataFrame

In [35]:
ICEdata = pd.read_csv("/Users/Wyr/Desktop/HUDK 4050/ICE/ICE 1/ICE1_Data.csv")

ICEdata

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
0    01M292           Developing                  C                      C   
1    01M448           Developing                  C                      B   
2    01M450       Well Developed                  A                      B   
3    01M509           Proficient                  C                      C   
4    01M539           Proficient                  A                      A   
..      ...                  ...                ...                    ...   
417  10X696       Well Developed                  A                      A   
418  13K430           Proficient                  B                      B   
419  10X445       Well Developed                  A                      A   
420  14K449       Well Developed                  B                      B   
421  28Q687           Proficient                  A                      B   

     graduation 2010-11  college enroll 2010-11  
0                 0.563                   0.519  
1                 0.707                   0.363  
2                 0.716                   0.692  
3                 0.564                   0.477  
4                 0.953                   0.870  
..                  ...                     ...  
417               1.000                   0.936  
418               0.977                   0.867  
419               1.000                   0.994  
420               0.914                   0.961  
421               1.000                   0.972  

[422 rows x 6 columns]

In [36]:
ICEdata['Quality_Review_Score']

0          Developing
1          Developing
2      Well Developed
3          Proficient
4          Proficient
            ...      
417    Well Developed
418        Proficient
419    Well Developed
420    Well Developed
421        Proficient
Name: Quality_Review_Score, Length: 422, dtype: object

#### Creating new columns

In [37]:
ICEdata['collegeRate'] = ICEdata['college enroll 2010-11'] / ICEdata['graduation 2010-11']
ICEdata

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
0    01M292           Developing                  C                      C   
1    01M448           Developing                  C                      B   
2    01M450       Well Developed                  A                      B   
3    01M509           Proficient                  C                      C   
4    01M539           Proficient                  A                      A   
..      ...                  ...                ...                    ...   
417  10X696       Well Developed                  A                      A   
418  13K430           Proficient                  B                      B   
419  10X445       Well Developed                  A                      A   
420  14K449       Well Developed                  B                      B   
421  28Q687           Proficient                  A                      B   

     graduation 2010-11  college enroll 2010-11  collegeRate  
0                 0.563                   0.519     0.921847  
1                 0.707                   0.363     0.513437  
2                 0.716                   0.692     0.966480  
3                 0.564                   0.477     0.845745  
4                 0.953                   0.870     0.912907  
..                  ...                     ...          ...  
417               1.000                   0.936     0.936000  
418               0.977                   0.867     0.887410  
419               1.000                   0.994     0.994000  
420               0.914                   0.961     1.051422  
421               1.000                   0.972     0.972000  

[422 rows x 7 columns]

In [38]:
ICEdata.loc[0]

DBN                           01M292
Quality_Review_Score      Developing
Progress_Rpt_10-11                 C
Student_Progress_10-11             C
graduation 2010-11             0.563
college enroll 2010-11         0.519
collegeRate                 0.921847
Name: 0, dtype: object

In [39]:
ICEdata.iloc[:3, :2]

DBN Quality_Review_Score
0  01M292           Developing
1  01M448           Developing
2  01M450       Well Developed

In [40]:
ICEdata.loc[:20, :'Progress_Rpt_10-11']

DBN Quality_Review_Score Progress_Rpt_10-11
0   01M292           Developing                  C
1   01M448           Developing                  C
2   01M450       Well Developed                  A
3   01M509           Proficient                  C
4   01M539           Proficient                  A
5   01M696       Well Developed                  B
6   02M047           Proficient                  C
7   02M288           Proficient                  A
8   02M294       Well Developed                  B
9   02M296           Proficient                  A
10  02M298       Well Developed                  A
11  02M300           Proficient                  B
12  02M303           Proficient                  B
13  02M305           Proficient                  C
14  02M308       Well Developed                  A
15  02M316           Proficient                  B
16  02M374           Proficient                  C
17  02M376       Well Developed                NaN
18  02M392           Proficient                NaN
19  02M393           Proficient                NaN
20  02M399           Proficient                NaN

In [41]:
ICEdata[ICEdata['graduation 2010-11'] > 0.75]

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
4    01M539           Proficient                  A                      A   
5    01M696       Well Developed                  B                      C   
7    02M288           Proficient                  A                      B   
9    02M296           Proficient                  A                      A   
10   02M298       Well Developed                  A                      A   
..      ...                  ...                ...                    ...   
417  10X696       Well Developed                  A                      A   
418  13K430           Proficient                  B                      B   
419  10X445       Well Developed                  A                      A   
420  14K449       Well Developed                  B                      B   
421  28Q687           Proficient                  A                      B   

     graduation 2010-11  college enroll 2010-11  collegeRate  
4                 0.953                   0.870     0.912907  
5                 0.976                   0.957     0.980533  
7                 0.820                   0.627     0.764634  
9                 0.793                   0.560     0.706179  
10                0.915                   0.796     0.869945  
..                  ...                     ...          ...  
417               1.000                   0.936     0.936000  
418               0.977                   0.867     0.887410  
419               1.000                   0.994     0.994000  
420               0.914                   0.961     1.051422  
421               1.000                   0.972     0.972000  

[135 rows x 7 columns]

## Data Masking

NumPy implements comparison operators such as < (less than) and > (greater than) as element-wise ufuncs. The result of these comparison operators is always an array with a Boolean data type. All six of the standard comparison operations are available:

- < or >: less than or greater than
- <= or >=: less than or equal to/greater than or equal to
- !=: Not equal to
- ==: Equal to; = is value assignment. Don't confuse them.

Below is an example of a simple array we have worked with:

In [42]:
m2

array([[9, 0, 0, 9],
       [3, 4, 0, 0],
       [4, 1, 7, 3]])

In [43]:
m2 < 2
# Notice here, m2 < 2 returns an array full of True and False marking which position(s) satisfy the criterium.

array([[False,  True,  True, False],
       [False, False,  True,  True],
       [False,  True, False, False]])

In [44]:
#And then we can use m2[m2 < 2] to access all the elements that satisfy the criterium.
m2[m2 < 2]

array([0, 0, 0, 0, 1])

But what if we want to know about all elements that are greater than 2 but smaller than 5?

This is accomplished through Python's bitwise logic operators,
- & (and),
- | (or) ,
- ^ (exclusive or),
- and ~(not).

In [45]:
mask = (m2 > 2) & (m2 <5)
# Writing the mask this way adds the readability
m2[mask]

array([3, 4, 4, 3])

In [46]:
ICEmask = (ICEdata['graduation 2010-11'] > 0.75) & (ICEdata['Progress_Rpt_10-11'] == 'A') & (ICEdata['Student_Progress_10-11'] == 'B')
ICEdata[ICEmask]

DBN                    Quality_Review_Score Progress_Rpt_10-11  \
7    02M288                              Proficient                  A   
25   02M412                              Proficient                  A   
75   04M435                          Well Developed                  A   
78   04M610                              Proficient                  A   
85   05M670                              Developing                  A   
107  07X548                              Proficient                  A   
108  07X551                              Proficient                  A   
147  09X543                          Well Developed                  A   
149  10X141                              Proficient                  A   
158  10X374                          Well Developed                  A   
161  10X437                              Developing                  A   
175  11X275                              Proficient                  A   
206  13K419                              Proficient                  A   
220  14K478                          Well Developed                  A   
251  17K531                              Proficient                  A   
274  19K404                          Well Developed                  A   
305  22K535                          Well Developed                  A   
308  23K514                              Proficient                  A   
334  26Q430                              Proficient                  A   
336  26Q495                          Well Developed                  A   
356  28Q440                              Proficient                  A   
357  28Q505                              Proficient                  A   
358  28Q620                          Well Developed                  A   
383  31R080                              Proficient                  A   
384  31R440                          Well Developed                  A   
413  03M485  Outstanding (only an option in 2007-8)                  A   
415  02M475                          Well Developed                  A   
416  05M692                          Well Developed                  A   
421  28Q687                              Proficient                  A   

    Student_Progress_10-11  graduation 2010-11  college enroll 2010-11  \
7                        B               0.820                   0.627   
25                       B               0.964                   0.774   
75                       B               0.920                   0.757   
78                       B               0.984                   0.982   
85                       B               0.789                   0.559   
107                      B               0.866                   0.663   
108                      B               0.831                   0.605   
147                      B               0.765                   0.319   
149                      B               0.870                   0.784   
158                      B               0.939                     NaN   
161                      B               0.855                   0.325   
175                      B               0.762                   0.517   
206                      B               0.802                   0.399   
220                      B               0.847                   0.432   
251                      B               0.787                   0.433   
274                      B               0.855                   0.538   
305                      B               0.958                   0.862   
308                      B               0.769                   0.467   
334                      B               0.875                   0.680   
336                      B               0.862                   0.745   
356                      B               0.844                   0.649   
357                      B               0.756                   0.529   
358                      B               0.877                   0.697   
383        

## Combining Datasets

In [47]:
def make_df(cols, ind):
    #Quickly make a DataFrame
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

# example DataFrame
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [48]:
# This is very similar to np.concatenate() or np.vstack(). 
# By default, the concatenation takes place row-wise within the DataFrame.

df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
print(df1, "\n\n\n")
print(df2, "\n\n\n")
print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2 



    A   B
3  A3  B3
4  A4  B4 



    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In practice, data from different sources might have different sets of column names, and pd.concat offers several options in this case.

Consider the concatenation of the following two DataFrames, which have some (but not all!) columns in common:

In [49]:
df3 = make_df('ABC', [1, 2])
df4 = make_df('BCD', [3, 4])
print(df3, "\n\n\n")
print(df4, "\n\n\n")
print(pd.concat([df3, df4]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2 



    B   C   D
3  B3  C3  D3
4  B4  C4  D4 



     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


By default, the entries for which no data is available are filled with NaN values. To change this, we can specify one of several options for the join parameters of the concatenate function.
- By default, the join is a union of the input columns (join='outer')
- but we can change this to an intersection of the columns using join='inner':

In [50]:
pd.concat([df3, df4], join = 'inner')

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

A more commonly used way is through pd.merge(). The pd.merge() function implements a number of types of joins: the one-to-one, many-to-one, and many-to-many joins (this is a bit conceptually confusing and I don't recommend using it unless you really need it).

All three types of joins are accessed via an identical call to the pd.merge() interface; the type of join performed depends on the form of the input data.

The simplest type of merge expresion is the one-to-one join, which is in many ways very similar to the column-wise concatenation seen previously. As a concrete example, consider the following two DataFrames which contain information on several employees in a company:

In [51]:
df5 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df6 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
dfm = pd.merge(df5, df6)

print(df5, "\n\n\n")
print(df6, "\n\n\n")
print(dfm)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR 



  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014 



  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


Many-to-one joins are joins in which one of the two key columns contains duplicate entries. For the many-to-one case, the resulting DataFrame will preserve those duplicate entries as appropriate. Consider the following example of a many-to-one join:

In [52]:
df7 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})

dfm = pd.merge(df5, df7)
print(df7, "\n\n\n")

print(dfm)

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve 



  employee        group supervisor
0      Bob   Accounting      Carly
1     Jake  Engineering      Guido
2     Lisa  Engineering      Guido
3      Sue           HR      Steve


The default behavior of pd.merge() is powerful: it looks for one or more matching column names between the two inputs, and uses this as the key. However, often the column names will not match so nicely, and pd.merge() provides a variety of options for handling this.

Most simply, you can explicitly specify the name of the key column using the on keyword, which takes a column name or a list of column names:

In [53]:
pd.merge(df5, df6, on='employee')

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

At times you may wish to merge two datasets with different column names;

for example, we may have a dataset in which the employee name is labeled as "name" rather than "employee". In this case, we can use the left_on and right_on keywords to specify the two column names:

In [54]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
pd.merge(df5, df8, left_on = 'employee', right_on = 'name')

employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

The redundant column can be dropped if desired (here axis = 1 means Whether to drop labels from the or columns.

See here: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html)

In [55]:
pd.merge(df5, df8, left_on = 'employee', right_on = 'name').drop('name', axis=1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

There are many more you can do with pd.merge(), such as:
- the left_index and right_index keywords allow you merge on an index instead.
- By default, the result contains the intersection of the two sets of inputs; this is what is known as an inner join. You can set how = inner, how = outer, how = left, and how = right. The missing values will be NaNs.
- Or in case, you have columns containing conflicting names, suffixes keyword to specify.

Read Pandas Documentation here https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html

Read a nice StackOverFlow post here on pd.merge(): https://stackoverflow.com/questions/53645882/pandas-merging-101

## Aggregation, grouping, and pivot tables

An essential piece of analysis of large data is efficient summarization: computing aggregations like sum(), mean(), median(), min(), and max(), in which a single number gives insight into the nature of a potentially large dataset. Last week, we used describe() function for quick-and-dirty summary. This week we will dive a bit deeper.

In [56]:
ICEdata.describe(include = 'all')

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
count      422                  368                310                    310   
unique     422                    6                  5                      5   
top     10X141           Proficient                  A                      C   
freq         1                  186                109                     93   
mean       NaN                  NaN                NaN                    NaN   
std        NaN                  NaN                NaN                    NaN   
min        NaN                  NaN                NaN                    NaN   
25%        NaN                  NaN                NaN                    NaN   
50%        NaN                  NaN                NaN                    NaN   
75%        NaN                  NaN                NaN                    NaN   
max        NaN                  NaN                NaN                    NaN   

        graduation 2010-11  college enroll 2010-11  collegeRate  
count           310.000000              291.000000   291.000000  
unique                 NaN                     NaN          NaN  
top                    NaN                     NaN          NaN  
freq                   NaN                     NaN          NaN  
mean              0.737977                0.531196     0.707836  
std               0.143356                0.193129     0.168986  
min               0.412000                0.141000     0.262570  
25%               0.625250                0.391000     0.589317  
50%               0.726000                0.489000     0.707569  
75%               0.850750                0.656000     0.838918  
max               1.000000                1.000000     1.101227

Simple methods such as sum(), mean(), median(), min(), and max() are pretty straight forward. They only work on numerical variables.

In [57]:
ICEdata.mean()

graduation 2010-11        0.737977
college enroll 2010-11    0.531196
collegeRate               0.707836
dtype: float64

In [58]:
ICEdata['graduation 2010-11'].max()

1.0

Other Pandas aggregation methods:
- count(): Total number of items
- first(), last(): First and last item
- mean(), median(): Mean and median
- min(), max(): Minimum and maximum
- std(), var(): Standard deviation and variance
- mad(): Mean absolute deviation
- prod(): Product of all items
- sum(): Sum of all items These are all methods of DataFrame and Series objects.

In [59]:
ICEdata['graduation 2010-11'].count()

310

In [60]:
ICEdata['graduation 2010-11'].mean()

0.7379774193548388

In [61]:
ICEdata['graduation 2010-11'].median()

0.726

In [62]:
ICEdata['graduation 2010-11'].min()

0.412

In [63]:
ICEdata['graduation 2010-11'].max()

1.0

In [64]:
ICEdata['graduation 2010-11'].std()

0.14335585931898884

In [65]:
ICEdata['graduation 2010-11'].var()

0.020550902401085716

In [66]:
ICEdata['graduation 2010-11'].mad()

0.11987933402705511

In [67]:
ICEdata['graduation 2010-11'].prod()

3.1250366929868145e-44

In [68]:
ICEdata['graduation 2010-11'].sum()

228.773

Simple aggregations only gives you a flavor of your dataset, but often we would prefer to aggregate conditionally on some label or index: this is implemented in the so-called "groupby" operation. The name "group by" comes from a command in the SQL database language and it is very commonly implemented in many other languages as well.

groupby generally follows three steps: split, apply, and combine:
- The split step involves breaking up and grouping a DataFrame depending on the value of the specified key.
- The apply step involves computing some function, usually an aggregate, transformation, or filtering, within the individual groups.
- The combine step merges the results of these operations into an output array.

These steps can certainly be done seperatedly and manually. The power of the groupby is that it abstracts away and automate these steps: you just need to thinks about the operation as a whole.

As a concrete example, let's take a look at the ICEdata we have been using. First, we will group it by the Quality_Review_Score, which has six levels: Developing, Well Developed, 'Proficient, nan, Underdeveloped,  Outstanding (only an option in 2007-8), and Underdeveloped with Proficient Features (only an option in 2007-8, 2008-9 and 2009-10)

In [69]:
ICEdata.groupby('Quality_Review_Score')

We then call the mean() methods to see the mean for each group.

In [70]:
ICEdata.groupby('Quality_Review_Score').mean()

graduation 2010-11  \
Quality_Review_Score                                                     
Developing                                                    0.633019   
Outstanding (only an option in 2007-8)                        0.864333   
Proficient                                                    0.729554   
Underdeveloped                                                0.549667   
Underdeveloped with Proficient Features (only a...                 NaN   
Well Developed                                                0.823367   

                                                    college enroll 2010-11  \
Quality_Review_Score                                                         
Developing                                                        0.402830   
Outstanding (only an option in 2007-8)                            0.747667   
Proficient                                                        0.521208   
Underdeveloped                                                    0.350167   
Underdeveloped with Proficient Features (only a...                     NaN   
Well Developed                                                    0.625871   

                                                    collegeRate  
Quality_Review_Score                                             
Developing                                             0.641309  
Outstanding (only an option in 2007-8)                 0.864183  
Proficient                                             0.703604  
Underdeveloped                                         0.631451  
Underdeveloped with Proficient Features (only a...          NaN  
Well Developed                                         0.752696

In [71]:
# We can also just simply index one column
ICEdata.groupby('Quality_Review_Score')['graduation 2010-11'].describe()

count      mean       std  \
Quality_Review_Score                                                            
Developing                                           53.0  0.633019  0.107199   
Outstanding (only an option in 2007-8)                3.0  0.864333  0.102051   
Proficient                                          157.0  0.729554  0.135946   
Underdeveloped                                        6.0  0.549667  0.061805   
Underdeveloped with Proficient Features (only a...    0.0       NaN       NaN   
Well Developed                                       90.0  0.823367  0.121570   

                                                      min      25%    50%  \
Quality_Review_Score                                                        
Developing                                          0.457  0.56300  0.615   
Outstanding (only an option in 2007-8)              0.800  0.80550  0.811   
Proficient                                          0.412  0.63000  0.722   
Underdeveloped                                      0.457  0.51525  0.554   
Underdeveloped with Proficient Features (only a...    NaN      NaN    NaN   
Well Developed                                      0.545  0.72775  0.833   

                                                        75%    max  
Quality_Review_Score                                                
Developing                                          0.69800  0.947  
Outstanding (only an option in 2007-8)              0.89650  0.982  
Proficient                                          0.81100  1.000  
Underdeveloped                                      0.59350  0.624  
Underdeveloped with Proficient Features (only a...      NaN    NaN  
Well Developed                                      0.91875  1.000

Or you can indicate multiple columns to group:

In [72]:
ICEdata.groupby(['Quality_Review_Score', 'Progress_Rpt_10-11']).count().unstack()
# Here unstack() is just to make the data more readable.
# See descriptions here: https://www.w3resource.com/pandas/dataframe/dataframe-unstack.php

DBN                         \
Progress_Rpt_10-11                         A     B     C     D    F   
Quality_Review_Score                                                  
Developing                               4.0  11.0  19.0  16.0  3.0   
Outstanding (only an option in 2007-8)   3.0   NaN   NaN   NaN  NaN   
Proficient                              48.0  65.0  39.0   5.0  NaN   
Underdeveloped                           NaN   NaN   3.0   1.0  2.0   
Well Developed                          53.0  26.0  11.0   NaN  NaN   

                                       Student_Progress_10-11              \
Progress_Rpt_10-11                                          A     B     C   
Quality_Review_Score                                                        
Developing                                                4.0  11.0  19.0   
Outstanding (only an option in 2007-8)                    3.0   NaN   NaN   
Proficient                                               48.0  65.0  39.0   
Underdeveloped                                            NaN   NaN   3.0   
Well Developed                                           53.0  26.0  11.0   

                                                   ... college enroll 2010-11  \
Progress_Rpt_10-11                         D    F  ...                      A   
Quality_Review_Score                               ...                          
Developing                              16.0  3.0  ...                    3.0   
Outstanding (only an option in 2007-8)   NaN  NaN  ...                    3.0   
Proficient                               5.0  NaN  ...                   45.0   
Underdeveloped                           1.0  2.0  ...                    NaN   
Well Developed                           NaN  NaN  ...                   48.0   

                                                              collegeRate  \
Progress_Rpt_10-11                         B     C     D    F           A   
Quality_Review_Score                                                        
Developing                              11.0  16.0  15.0  2.0         3.0   
Outstanding (only an option in 2007-8)   NaN   NaN   NaN  NaN         3.0   
Proficient                              63.0  37.0   4.0  NaN        45.0   
Underdeveloped                           NaN   3.0   1.0  2.0         NaN   
Well Developed                          26.0  11.0   NaN  NaN        48.0   

                                                               
Progress_Rpt_10-11                         B     C     D    F  
Quality_Review_Score                                           
Developing                              11.0  16.0  15.0  2.0  
Outstanding (only an option in 2007-8)   NaN   NaN   NaN  NaN  
Proficient                              63.0  37.0   4.0  NaN  
Underdeveloped                           NaN   3.0   1.0  2.0  
Well Developed                          26.0  11.0   NaN  NaN  

[5 rows x 25 columns]

We're now familiar with groupby aggregations with sum(), median(), and the like, but the aggregate() method allows for even more flexibility. It can take a string, a function, or a list thereof, and compute all the aggregates at once. Here is a quick example combining all these:

In [73]:
ICEdata.groupby('Quality_Review_Score').aggregate(['median', 'min', 'max'])

graduation 2010-11         \
                                                               median    min   
Quality_Review_Score                                                           
Developing                                                      0.615  0.457   
Outstanding (only an option in 2007-8)                          0.811  0.800   
Proficient                                                      0.722  0.412   
Underdeveloped                                                  0.554  0.457   
Underdeveloped with Proficient Features (only a...                NaN    NaN   
Well Developed                                                  0.833  0.545   

                                                           \
                                                      max   
Quality_Review_Score                                        
Developing                                          0.947   
Outstanding (only an option in 2007-8)              0.982   
Proficient                                          1.000   
Underdeveloped                                      0.624   
Underdeveloped with Proficient Features (only a...    NaN   
Well Developed                                      1.000   

                                                   college enroll 2010-11  \
                                                                   median   
Quality_Review_Score                                                        
Developing                                                         0.4030   
Outstanding (only an option in 2007-8)                             0.6920   
Proficient                                                         0.4900   
Underdeveloped                                                     0.3715   
Underdeveloped with Proficient Features (only a...                    NaN   
Well Developed                                                     0.5920   

                                                                 collegeRate  \
                                                      min    max      median   
Quality_Review_Score                                                           
Developing                                          0.165  0.658    0.647416   
Outstanding (only an option in 2007-8)              0.690  0.861    0.862500   
Proficient                                          0.183  0.990    0.699735   
Underdeveloped                                      0.141  0.465    0.712859   
Underdeveloped with Proficient Features (only a...    NaN    NaN         NaN   
Well Developed                                      0.268  1.000    0.765269   

                                                                        
                                                         min       max  
Quality_Review_Score                                                    
Developing                                          0.271829  1.048622  
Outstanding (only an option in 2007-8)              0.853268  0.876782  
Proficient                                          0.296503  1.101227  
Underdeveloped                                      0.262570  0.756567  
Underdeveloped with Proficient Features (only a...       NaN       NaN  
Well Developed                                      0.388970  1.051422

Similarly, you can go further and request the median data of graduation 2010-11 for Quality_Review_Score, Progress_Rpt_10-11:

In [74]:
ICEdata.groupby(['Quality_Review_Score', 'Progress_Rpt_10-11'])['graduation 2010-11'].aggregate('median').unstack()

Progress_Rpt_10-11                          A       B      C      D      F
Quality_Review_Score                                                      
Developing                              0.702  0.6290  0.587  0.615  0.506
Outstanding (only an option in 2007-8)  0.811     NaN    NaN    NaN    NaN
Proficient                              0.806  0.7150  0.662  0.531    NaN
Underdeveloped                            NaN     NaN  0.537  0.457  0.586
Well Developed                          0.879  0.8145  0.676    NaN    NaN

This two-dimensional groupby is common enough that Pandas includes a convenience routine, pivot_table, which succinctly handles this type of multi-dimensional aggregation, and hopefully, makes more sense than the previous line.

In [75]:
ICEdata.pivot_table('graduation 2010-11', index='Quality_Review_Score', columns='Progress_Rpt_10-11')

Progress_Rpt_10-11                             A         B         C  \
Quality_Review_Score                                                   
Developing                              0.716500  0.654545  0.639474   
Outstanding (only an option in 2007-8)  0.864333       NaN       NaN   
Proficient                              0.817083  0.722077  0.660333   
Underdeveloped                               NaN       NaN  0.556333   
Well Developed                          0.862472  0.791000  0.711455   

Progress_Rpt_10-11                             D         F  
Quality_Review_Score                                        
Developing                              0.613812  0.504333  
Outstanding (only an option in 2007-8)       NaN       NaN  
Proficient                              0.526400       NaN  
Underdeveloped                          0.457000  0.586000  
Well Developed                               NaN       NaN

By default, pivot_table uses mean as the aggregation method. You can certainly tell Python what do you want through the aggfunc keyword.

Read more about pivot_table() here: https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html and https://pbpython.com/pandas-pivot-table-explained.html

In [76]:
ICEdata.pivot_table('graduation 2010-11',
                    index='Quality_Review_Score',
                    columns='Progress_Rpt_10-11',
                   aggfunc = 'median')

Progress_Rpt_10-11                          A       B      C      D      F
Quality_Review_Score                                                      
Developing                              0.702  0.6290  0.587  0.615  0.506
Outstanding (only an option in 2007-8)  0.811     NaN    NaN    NaN    NaN
Proficient                              0.806  0.7150  0.662  0.531    NaN
Underdeveloped                            NaN     NaN  0.537  0.457  0.586
Well Developed                          0.879  0.8145  0.676    NaN    NaN

## More data wrangling

Data wrangling cheatsheet/tutorial:
- Pandas Cheat Sheet: Data Wrangling in Python
http://datacamp-community-prod.s3.amazonaws.com/d4efb29b-f9c6-4f1c-8c98-6f568d88b48f
- Data wrangling with pandas cheat sheet
http://ow.ly/2ur1309Txlr
- Python Data Science Handbook
https://jakevdp.github.io/PythonDataScienceHandbook/index.html
- Data Wrangling with Python and Pandas - Workshop:
https://youtu.be/6rDqwji7eMc
A lengthy video tutorial.